; غیرفعال کردن کامل opcache
opcache.enable=0
opcache.enable_cli=0

; مسیر session قابل نوشتن
session.save_path=/data/data/com.termux/files/home/neurocms/storage/framework/sessions

; مسیر upload موقت
upload_tmp_dir=/data/data/com.termux/files/home/neurocms/storage/framework/cache

; غیرفعال کردن file locking session
session.use_strict_mode=0

; غیرفعال کردن syslog (گاهی در termux مشکل‌ساز است)
error_log=/data/data/com.termux/files/home/neurocms/storage/logs/php-error.log
